spring:
  application:
    name: demo-ftppool
  devtools:
    restart:
      enabled: false
server:
  port: 8080
  servlet:
    context-path: /demoFtpPool
    
plugin:
  ftp-pool:
    host: 192.168.100.101
    port: 21
    username: ftpuser
    password: 123456
    projectRoot: /
    connectTimeOut: 30000
    passiveMode: false
  xss-filter:
    exclude:
      exclude-path:
      - /ftpDemo/**
      - /xssDemo/unFilter
  
